
set -ga terminal-overrides ",xterm-kitty:Tc"
set -as terminal-features ",xterm-kitty:RGB,usstyle"

set -g set-clipboard on
set -g allow-passthrough on        # laisse helix émettre ses propres OSC52

set -g focus-events on             
setw -g pane-base-index 1
set -g renumber-windows on

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window      -c "#{pane_current_path}"

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

bind r source-file ~/.config/tmux/tmux.conf \; display "tmux.conf rechargé"

bind g display-popup -E -d "#{pane_current_path}" -w 90% -h 90% "lazygit"
bind b display-popup -E -w 80% -h 80% "btop"

bind o display-popup -E -w 70% -h 60% "\
dir=\$(zoxide query -l | fzf --reverse --prompt='project> ') || exit 0; \
name=\$(basename \"\$dir\" | tr '. ' '__'); \
tmux new-session -d -s \"\$name\" -c \"\$dir\" 2>/dev/null; \
tmux switch-client -t \"\$name\""
